extends Control
## Full-screen informational world map (toggle with M). Draws every map as a node
## on a hand-authored regional layout, edges from the real portal graph, and the
## player's current location highlighted. All locations are shown (no fog); hover
## a map for a tooltip with its recommended level, the enemies that live there
## (with levels), and each enemy's drop table with drop %.
##
## Pure client-side: content comes from the static catalog config/world_map_data.json
## (built by tools/dump_world_map.gd from the same scenes/portals the game uses).
## No RPCs, no state mutation.

const CATALOG_PATH := "res://config/world_map_data.json"

## Normalized [0..1] node positions within the content rect, laid out as the RADIAL "Sleepywood"
## wheel: a low OUTER RING of cities + fields around the rim, three SPOKES angling inward and
## converging at the central Hearth Emberwatch, then a CORE spiral winding down to the Warlord at
## the dead centre (0.5, 0.5) — radius ≈ distance from the wound, so deeper = nearer the middle.
## (The content rect is landscape, so the circle reads as a wide oval.) Presentation only — edges
## come from the real connection graph. ADD EVERY NEW MAP HERE, or it won't render (piles at centre).
## Generated by tools/preview_world_map.py (TURNS=1.35, R_START=0.56, R_FLOOR=0.15) — re-run
## that tool to preview/retune, then paste its printed block here. Tuned for a ~1.9:1 rect.
const LAYOUT := {
	# --- Outer ring: low cities + fields around the rim ---
	"lanterns_rest":   Vector2(0.500, 0.070),
	"near_wilds":      Vector2(0.796, 0.171),
	"meadow_path":     Vector2(0.953, 0.425),
	"wickmoor":        Vector2(0.898, 0.715),
	"tinderfields":    Vector2(0.657, 0.904),
	"ember_meadows":   Vector2(0.343, 0.904),
	"hollowmere":      Vector2(0.102, 0.715),
	"bramble_downs":   Vector2(0.047, 0.425),
	"brackenway":      Vector2(0.204, 0.171),
	# --- Central Hearth (spokes converge) ---
	"emberwatch":      Vector2(0.521, 0.677),
	# --- Spoke 1 + Core: the rim-to-centre spiral ---
	"ruins":           Vector2(0.500, 0.259),
	"old_battlefield": Vector2(0.639, 0.312),
	"thornroot":       Vector2(0.716, 0.424),
	"mines":           Vector2(0.711, 0.550),
	"the_undercroft":  Vector2(0.634, 0.643),
	"deep_woods":      Vector2(0.416, 0.646),
	"keep":            Vector2(0.354, 0.569),
	"mustering_fields":Vector2(0.352, 0.481),
	"the_scorchline":  Vector2(0.399, 0.414),
	"emberscar":       Vector2(0.473, 0.388),
	"cinderwaste":     Vector2(0.541, 0.405),
	"weave":           Vector2(0.580, 0.451),
	"the_unraveling":  Vector2(0.582, 0.502),
	"ashvigil":        Vector2(0.556, 0.538),
	"warlord":         Vector2(0.500, 0.500),
	# --- Spoke 2 (Wickmoor -> Emberwatch) + Spoke 3 (Hollowmere -> Emberwatch) ---
	"three_terraces":  Vector2(0.804, 0.705),
	"bandit_bluffs":   Vector2(0.710, 0.696),
	"dust_warren":     Vector2(0.616, 0.686),
	"mirefen":         Vector2(0.242, 0.702),
	"stonereach":      Vector2(0.381, 0.689),
}
# Hearth (safe town) maps come from MapManager.HEARTH_MAPS — single source of
# truth shared with Hearthstone/Town-Scroll teleport targeting.

const C_BG := Color(0.03, 0.04, 0.07, 0.92)
const C_EDGE := Color(0.55, 0.5, 0.35, 0.7)
const C_TOWN := Color(1.0, 0.82, 0.3)
const C_VISITED := Color(0.5, 0.78, 0.55)
const C_BOSS := Color(0.95, 0.4, 0.4)
const C_FOG := Color(0.22, 0.23, 0.28)
const C_CURRENT := Color(0.45, 0.85, 1.0)
const NODE_R := 13.0

var _catalog: Dictionary = {}
var _font: Font
var _tip: PanelContainer        # styled tooltip card
var _tip_scroll: ScrollContainer  # caps card height; scrolls when content is tall
var _tip_body: VBoxContainer    # rebuilt per hovered map
var _tip_tween: Tween
var _sf_cache: Dictionary = {}  # sprite-frames path -> first-frame Texture2D
var _icon_cache: Dictionary = {}  # item icon path -> Texture2D
var _hovered: String = ""
var _pulse: float = 0.0


func _ready() -> void:
	set_anchors_preset(Control.PRESET_FULL_RECT)
	mouse_filter = Control.MOUSE_FILTER_STOP
	visible = false
	_font = ThemeDB.fallback_font
	_load_catalog()

	_tip = PanelContainer.new()
	_tip.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_tip.custom_minimum_size = Vector2(320, 0)
	_tip.z_index = 20
	var sb := StyleBoxFlat.new()
	sb.bg_color = Color(0.07, 0.08, 0.12, 0.98)
	sb.border_color = Color(0.95, 0.85, 0.45, 0.85)
	sb.set_border_width_all(2)
	sb.set_corner_radius_all(8)
	sb.content_margin_left = 14
	sb.content_margin_right = 14
	sb.content_margin_top = 12
	sb.content_margin_bottom = 12
	sb.shadow_color = Color(0, 0, 0, 0.55)
	sb.shadow_size = 10
	_tip.add_theme_stylebox_override("panel", sb)
	# A scroll wrapper caps the card height so a drop-heavy map can't run off the
	# screen; it only scrolls when the content exceeds the cap (see _update_hover).
	_tip_scroll = ScrollContainer.new()
	_tip_scroll.horizontal_scroll_mode = ScrollContainer.SCROLL_MODE_DISABLED
	_tip_scroll.vertical_scroll_mode = ScrollContainer.SCROLL_MODE_AUTO
	_tip_scroll.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_tip.add_child(_tip_scroll)
	_tip_body = VBoxContainer.new()
	_tip_body.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_tip_body.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	_tip_body.add_theme_constant_override("separation", 8)
	_tip_scroll.add_child(_tip_body)
	_tip.visible = false
	add_child(_tip)
	# Join the standard window group so player_hud's Esc / death handlers close it
	# like every other window. Closing may happen via .visible (player_hud) OR
	# toggle() (M key), so the open/close side-effects live in _on_visibility_changed.
	add_to_group("ui_window")
	visibility_changed.connect(_on_visibility_changed)
	MapManager.population_counts_received.connect(_on_population_counts)
	set_process(false)


func _load_catalog() -> void:
	if not FileAccess.file_exists(CATALOG_PATH):
		push_warning("world_map: missing %s — run tools/dump_world_map.gd" % CATALOG_PATH)
		return
	var f := FileAccess.open(CATALOG_PATH, FileAccess.READ)
	var parsed = JSON.parse_string(f.get_as_text())
	if parsed is Dictionary:
		_catalog = parsed.get("maps", {})


func toggle() -> void:
	visible = not visible


func _on_visibility_changed() -> void:
	set_process(visible)
	if visible:
		_pulse = 0.0
		move_to_front()
		# One population snapshot per open (ADR 0012) — counts players + bots.
		if multiplayer.has_multiplayer_peer():
			MapManager.request_population_counts.rpc_id(1)
	else:
		_hovered = ""
		_tip.visible = false


## Per-map occupant counts (players + bots), refreshed each time the map opens.
var _population: Dictionary = {}

func _on_population_counts(counts: Dictionary) -> void:
	_population = counts
	queue_redraw()


func _unhandled_key_input(event: InputEvent) -> void:
	# M toggles the map open/closed. (Esc-to-close is handled by player_hud via the
	# "ui_window" group, the same as every other window; this is just a fallback.)
	if event is InputEventKey and event.pressed and not event.echo:
		if event.keycode == KEY_M and not InputManager.is_locked():
			toggle()
			get_viewport().set_input_as_handled()
		elif event.keycode == KEY_ESCAPE and visible:
			visible = false
			get_viewport().set_input_as_handled()


## Maps the player has revealed: server-saved visited set + the live current map.
## All locations are shown on the world map (no fog) — every map is discoverable
## at a glance. (The current location is still highlighted in _draw.)
func _revealed() -> Dictionary:
	var s := {}
	for map_id in _catalog:
		s[map_id] = true
	return s


func _content_rect() -> Rect2:
	var m := 70.0
	return Rect2(m, m + 24.0, size.x - m * 2.0, size.y - m * 2.0 - 24.0)


func _node_pos(map_id: String, content: Rect2) -> Vector2:
	var n: Vector2 = LAYOUT.get(map_id, Vector2(0.5, 0.5))
	return content.position + n * content.size


func _process(delta: float) -> void:
	if not visible:
		return
	_pulse += delta
	_update_hover()
	queue_redraw()


func _update_hover() -> void:
	var content := _content_rect()
	var mouse := get_local_mouse_position()
	var found := ""
	for map_id in LAYOUT:
		if not _catalog.has(map_id):
			continue
		if mouse.distance_to(_node_pos(map_id, content)) <= NODE_R + 4.0:
			found = map_id
			break
	if found != _hovered:
		_hovered = found
		if found == "":
			_tip.visible = false
		else:
			_build_tip(found)
	if _tip.visible:
		# Size the scroll area to its content, capped at the available screen height
		# (so a drop-heavy map scrolls instead of overflowing). Then shrink the card
		# to that and clamp near the cursor.
		var content_h: float = _tip_body.get_combined_minimum_size().y
		var max_h: float = maxf(120.0, size.y - 24.0)
		_tip_scroll.custom_minimum_size.y = minf(content_h, max_h)
		_tip.reset_size()
		var pos := mouse + Vector2(20, 14)
		pos.x = clampf(pos.x, 8.0, maxf(8.0, size.x - _tip.size.x - 8.0))
		pos.y = clampf(pos.y, 8.0, maxf(8.0, size.y - _tip.size.y - 8.0))
		_tip.position = pos


## The card ignores the mouse (so hovering it doesn't drop the node hover), so we
## route wheel scrolling to it here while it's showing and taller than its cap.
func _gui_input(event: InputEvent) -> void:
	if not _tip.visible:
		return
	if event is InputEventMouseButton and event.pressed:
		if event.button_index == MOUSE_BUTTON_WHEEL_DOWN:
			_tip_scroll.scroll_vertical += 36
			accept_event()
		elif event.button_index == MOUSE_BUTTON_WHEEL_UP:
			_tip_scroll.scroll_vertical -= 36
			accept_event()


## Rebuild the tooltip card for a map and pop it in.
func _build_tip(map_id: String) -> void:
	for c in _tip_body.get_children():
		_tip_body.remove_child(c)
		c.queue_free()

	var info: Dictionary = _catalog.get(map_id, {})
	var dname: String = MapManager.MAP_DISPLAY_NAMES.get(map_id, info.get("display_name", map_id))
	var is_town: bool = (map_id in MapManager.HEARTH_MAPS) or info.get("is_town", false)
	var has_boss := false
	for e in info.get("enemies", []):
		if e.get("is_boss", false):
			has_boss = true

	# Header: title + level / SAFE badge.
	var header := HBoxContainer.new()
	header.add_theme_constant_override("separation", 10)
	var title := _label(("★ " if has_boss else "") + dname, 20, Color(1.0, 0.9, 0.62))
	title.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	title.size_flags_vertical = Control.SIZE_SHRINK_CENTER
	header.add_child(title)
	if is_town:
		header.add_child(_badge("SAFE", Color(0.45, 0.4, 0.16)))
	else:
		header.add_child(_badge("Lv %d" % int(info.get("avg_level", 0)),
			Color(0.65, 0.32, 0.32) if has_boss else Color(0.18, 0.46, 0.6)))
	_tip_body.add_child(header)

	if not is_town:
		var sub := _label("Recommended  ·  enemies Lv %d–%d" % [int(info.get("min_level", 0)), int(info.get("max_level", 0))],
			12, Color(0.6, 0.65, 0.72))
		_tip_body.add_child(sub)
	_tip_body.add_child(_hsep())

	if is_town:
		_tip_body.add_child(_label("A safe hearth — no enemies here.", 14, Color(1.0, 0.85, 0.45)))
	else:
		for e in info.get("enemies", []):
			_tip_body.add_child(_make_enemy_row(e))

	_tip_scroll.scroll_vertical = 0
	_tip.visible = true
	_pop_in()


func _make_enemy_row(e: Dictionary) -> Control:
	var row := HBoxContainer.new()
	row.add_theme_constant_override("separation", 10)

	# Sprite thumbnail in a soft framed box.
	var frame := PanelContainer.new()
	var fsb := StyleBoxFlat.new()
	fsb.bg_color = Color(0, 0, 0, 0.28)
	fsb.set_corner_radius_all(6)
	frame.add_theme_stylebox_override("panel", fsb)
	frame.size_flags_vertical = Control.SIZE_SHRINK_CENTER
	var tex_rect := TextureRect.new()
	tex_rect.custom_minimum_size = Vector2(46, 46)
	tex_rect.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	tex_rect.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	tex_rect.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	var tex := _enemy_tex(e.get("sf", ""))
	if tex:
		tex_rect.texture = tex
	frame.add_child(tex_rect)
	row.add_child(frame)

	var col := VBoxContainer.new()
	col.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	col.add_theme_constant_override("separation", 1)
	var boss_tag: String = "  [color=#ff7676]BOSS[/color]" if e.get("is_boss", false) else ""
	col.add_child(_rich("[b]%s[/b]  [color=#8a93a0]Lv %d[/color]%s" % [e.get("name", "?"), int(e.get("level", 0)), boss_tag], 14))
	# Item drops (Coin omitted — it's not interesting loot).
	var loot := []
	for d in e.get("drops", []):
		if String(d.get("item", "")) != "Coin":
			loot.append(d)
	if loot.is_empty():
		col.add_child(_rich("[color=#666]no item drops[/color]", 12))
	else:
		for d in loot:
			col.add_child(_make_drop_row(d))
	row.add_child(col)
	return row


func _make_drop_row(d: Dictionary) -> Control:
	var h := HBoxContainer.new()
	h.add_theme_constant_override("separation", 6)
	var ic := TextureRect.new()
	ic.custom_minimum_size = Vector2(20, 20)
	ic.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	ic.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	ic.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	ic.size_flags_vertical = Control.SIZE_SHRINK_CENTER
	var tex := _item_icon(d.get("icon", ""))
	if tex:
		ic.texture = tex
	h.add_child(ic)
	var pct: float = float(d.get("chance", 0.0)) * 100.0
	var pct_str: String = ("%.1f%%" % pct) if pct < 10.0 else ("%d%%" % int(round(pct)))
	var lvl: int = int(d.get("ilvl", 0))
	var lvl_str: String = ("  [color=#7a8190]Lv %d[/color]" % lvl) if lvl > 0 else ""
	h.add_child(_rich("[color=#c2cee0]%s[/color]%s   [color=#7fd0a0]%s[/color]" % [d.get("item", "?"), lvl_str, pct_str], 12))
	return h


func _item_icon(path: String) -> Texture2D:
	if path == "":
		return null
	if _icon_cache.has(path):
		return _icon_cache[path]
	var t = load(path)
	var tex: Texture2D = t if t is Texture2D else null
	_icon_cache[path] = tex
	return tex


func _enemy_tex(sf_path: String) -> Texture2D:
	if sf_path == "":
		return null
	if _sf_cache.has(sf_path):
		return _sf_cache[sf_path]
	var tex: Texture2D = null
	var sf = load(sf_path)
	if sf is SpriteFrames:
		var anim := ""
		for cand in ["idle", "default", "walk"]:
			if sf.has_animation(cand):
				anim = cand
				break
		if anim == "" and sf.get_animation_names().size() > 0:
			anim = sf.get_animation_names()[0]
		if anim != "" and sf.get_frame_count(anim) > 0:
			tex = sf.get_frame_texture(anim, 0)
	_sf_cache[sf_path] = tex
	return tex


func _label(text: String, sz: int, col: Color) -> Label:
	var l := Label.new()
	l.text = text
	l.mouse_filter = Control.MOUSE_FILTER_IGNORE
	l.add_theme_font_size_override("font_size", sz)
	l.add_theme_color_override("font_color", col)
	return l


func _rich(bb: String, sz: int) -> RichTextLabel:
	var r := RichTextLabel.new()
	r.bbcode_enabled = true
	r.fit_content = true
	r.scroll_active = false
	r.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	r.mouse_filter = Control.MOUSE_FILTER_IGNORE
	r.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	r.add_theme_font_size_override("normal_font_size", sz)
	r.add_theme_font_size_override("bold_font_size", sz)
	r.text = bb
	return r


func _badge(text: String, col: Color) -> Control:
	var p := PanelContainer.new()
	p.size_flags_vertical = Control.SIZE_SHRINK_CENTER
	var sb := StyleBoxFlat.new()
	sb.bg_color = col
	sb.set_corner_radius_all(6)
	sb.content_margin_left = 9
	sb.content_margin_right = 9
	sb.content_margin_top = 3
	sb.content_margin_bottom = 3
	p.add_theme_stylebox_override("panel", sb)
	p.add_child(_label(text, 13, Color(1, 1, 1, 0.95)))
	return p


func _hsep() -> Control:
	var c := ColorRect.new()
	c.color = Color(1, 1, 1, 0.12)
	c.custom_minimum_size = Vector2(0, 1)
	return c


func _pop_in() -> void:
	if _tip_tween and _tip_tween.is_valid():
		_tip_tween.kill()
	_tip.pivot_offset = Vector2.ZERO
	_tip.modulate.a = 0.0
	_tip.scale = Vector2(0.95, 0.95)
	_tip_tween = create_tween().set_parallel(true).set_ease(Tween.EASE_OUT)
	_tip_tween.tween_property(_tip, "modulate:a", 1.0, 0.12).set_trans(Tween.TRANS_SINE)
	_tip_tween.tween_property(_tip, "scale", Vector2.ONE, 0.20).set_trans(Tween.TRANS_BACK)


func _draw() -> void:
	draw_rect(Rect2(Vector2.ZERO, size), C_BG, true)
	var content := _content_rect()
	if _font:
		draw_string(_font, Vector2(content.position.x, 50), "World Map — The Emberwilds",
			HORIZONTAL_ALIGNMENT_LEFT, -1, 22, Color(1, 0.9, 0.6))
		draw_string(_font, Vector2(content.position.x, content.end.y + 36), "[M] or [Esc] to close",
			HORIZONTAL_ALIGNMENT_LEFT, -1, 13, Color(0.6, 0.6, 0.65))

	var revealed := _revealed()

	# Edges (undirected, drawn once) — only between maps that exist in the layout.
	var drawn := {}
	for map_id in _catalog:
		if not LAYOUT.has(map_id):
			continue
		for tgt in _catalog[map_id].get("connections", []):
			if not LAYOUT.has(tgt):
				continue
			var key: String = map_id + "|" + tgt if map_id < tgt else tgt + "|" + map_id
			if drawn.has(key):
				continue
			drawn[key] = true
			var both_seen: bool = revealed.has(map_id) and revealed.has(tgt)
			var col: Color = C_EDGE if both_seen else Color(C_FOG, 0.5)
			draw_line(_node_pos(map_id, content), _node_pos(tgt, content), col, 2.0)

	# Nodes
	for map_id in LAYOUT:
		if not _catalog.has(map_id):
			continue
		var p := _node_pos(map_id, content)
		var info: Dictionary = _catalog[map_id]
		var seen: bool = revealed.has(map_id)
		var is_current: bool = (map_id == MapManager.current_map_id)
		var has_boss := false
		for e in info.get("enemies", []):
			if e.get("is_boss", false):
				has_boss = true
		var col: Color = C_FOG
		if seen:
			if (map_id in MapManager.HEARTH_MAPS) or info.get("is_town", false):
				col = C_TOWN
			elif has_boss:
				col = C_BOSS
			else:
				col = C_VISITED
		var r: float = NODE_R + (2.0 if ((map_id in MapManager.HEARTH_MAPS) or has_boss) else 0.0)

		if is_current:
			var glow: float = 0.5 + 0.5 * sin(_pulse * 4.0)
			draw_arc(p, r + 6.0, 0, TAU, 32, Color(C_CURRENT, 0.4 + 0.5 * glow), 3.0)
		draw_circle(p, r, col)
		draw_arc(p, r, 0, TAU, 28, Color(0, 0, 0, 0.6), 1.5)
		if _hovered == map_id:
			draw_arc(p, r + 3.0, 0, TAU, 28, Color.WHITE, 1.5)

		if _font:
			if seen:
				var dname: String = MapManager.MAP_DISPLAY_NAMES.get(map_id, info.get("display_name", map_id))
				draw_string(_font, p + Vector2(-60, r + 14), dname,
					HORIZONTAL_ALIGNMENT_CENTER, 120, 12, Color(0.92, 0.92, 0.95))
				# Population badge (ADR 0012) — revealed maps only, so fog of
				# war doesn't leak where the action is.
				var pop: int = int(_population.get(map_id, 0))
				if pop > 0:
					draw_circle(p + Vector2(r + 5, -r - 2), 7.0, Color(0.12, 0.3, 0.16, 0.9))
					draw_string(_font, p + Vector2(r + 5 - 8, -r + 2), str(pop),
						HORIZONTAL_ALIGNMENT_CENTER, 16, 10, Color(0.6, 1.0, 0.65))
			else:
				draw_string(_font, p + Vector2(-5, 5), "?",
					HORIZONTAL_ALIGNMENT_LEFT, -1, 16, Color(0.6, 0.6, 0.65))
