#!/usr/bin/env python3
"""Render docs/damage_matrix_report.md from docs/damage_matrix_dump.json
(produced by tools/damage_matrix.gd) and run the inconsistency sweep.

Damage model (mirrors combat.gd):
  avg_hit(build, ability) = mean(uniform(mastery*max_range, max_range)) * dmg%/100
  per_cast  = avg_hit * max(1,targets) * max(1,hits)   (full-AoE potential)
  dps       = per_cast / cooldown ; dpm = per_cast / mana
"""
import json, os, statistics

HERE = os.path.dirname(os.path.abspath(__file__))
D = json.load(open(os.path.join(HERE, "..", "docs", "damage_matrix_dump.json")))
OUT = os.path.join(HERE, "..", "docs", "damage_matrix_report.md")

WEAPONS = ["Sword", "Bow", "Staff", "Dagger"]
LEVELS = [1, 5, 10]
WPN_ATK, MAG_ATK = "12", "13"
META = D["meta"]
issues = []


def avg_roll(build, dmg_stat):
    mr = build["max_range_by_stat"][str(dmg_stat)]
    m = build["mastery_floor"]
    return mr * (1.0 + m) / 2.0


# Ground-zone abilities never land a direct hit: damage_percent is the
# PER-TICK fraction (dot_scaling_base) and the zone ticks duration/interval
# times (AL_Stormcall.gd "2026-06-11 fix" comment; same shape in the others).
ZONE_KEYS = {"Stormcall": "stormcall", "Sky Volley": "sky_volley",
             "Frost Patch": "frost_patch", "Caltrops": "caltrops"}


def zone_ticks(name):
    sc = META["script_constants"][ZONE_KEYS[name]]
    return sc["ZONE_DURATION"] / sc["ZONE_TICK_INTERVAL"]


def per_cast(build, ab, lvl):
    ls = ab["levels"][str(lvl)]
    hit = avg_roll(build, ab["damage_stat"]) * ls["damage_percent"] / 100.0
    if ab["name"] in ZONE_KEYS:
        return hit, hit * zone_ticks(ab["name"]) * max(1, ls["targets"])
    return hit, hit * max(1, ls["targets"]) * max(1, ls["hits"])


lines = ["# Damage matrix — weapons, levels 1/5/10, pairs, staff elements",
         "",
         "Generated by `tools/damage_matrix.gd` (real components/resources) + "
         "`tools/damage_matrix_report.py`. Damage figures are average rolls "
         "(`mastery_floor=%.1f` -> avg = %.1f x max_range), full-AoE potential." % (
             D["builds"]["Sword_L1"]["mastery_floor"],
             (1 + D["builds"]["Sword_L1"]["mastery_floor"]) / 2), ""]

# ── builds ───────────────────────────────────────────────────────────────────
lines += ["## Character builds (bot-allocated attributes + tier gear)", "",
          "| Build | Weapon | Primary | Secondary | max_range (phys) | max_range (magic) |",
          "|---|---|---|---|---|---|"]
for w in WEAPONS:
    for L in LEVELS:
        b = D["builds"][f"{w}_L{L}"]
        lines.append("| %s L%d | %s | %d | %d | %d | %d |" % (
            w, L, b["weapon"], b["primary"], b["secondary"],
            b["max_range_by_stat"][WPN_ATK], b["max_range_by_stat"][MAG_ATK]))
lines.append("")

# ── per-weapon ability tables ────────────────────────────────────────────────
for w in WEAPONS:
    lines += [f"## {w} — damage abilities (char level == ability level column)", "",
              "| Ability | L1 cast | L1 dps | L5 cast | L5 dps | L10 cast | L10 dps | L10 mana | L10 dpm |",
              "|---|---|---|---|---|---|---|---|---|"]
    for ab in sorted(D["abilities"][w], key=lambda a: -per_cast(D["builds"][f"{w}_L10"], a, 10)[1]):
        if all(ab["levels"][str(l)]["damage_percent"] == 0 for l in LEVELS):
            continue  # pure buff/utility
        row = [ab["name"]]
        for L in LEVELS:
            b = D["builds"][f"{w}_L{L}"]
            hit, cast = per_cast(b, ab, L)
            cd = ab["levels"][str(L)]["cooldown"]
            row += ["%.0f" % cast, ("%.1f" % (cast / cd)) if cd > 0 else "inst"]
        ls10 = ab["levels"]["10"]
        b10 = D["builds"][f"{w}_L10"]
        _, cast10 = per_cast(b10, ab, 10)
        row += ["%d" % ls10["mana"], ("%.1f" % (cast10 / ls10["mana"])) if ls10["mana"] else "free"]
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")

# ── staff elements ───────────────────────────────────────────────────────────
e = META["element"]
lines += ["## Staff element riders (per spell hit that lands)", "",
          "| Element | Effect on hit | Value at Staff L1 / L5 / L10 (vs avg Arcane Bolt hit) |",
          "|---|---|---|"]
bolt = next(a for a in D["abilities"]["Staff"] if a["name"] == "Arcane Bolt")
vals = {}
for L in LEVELS:
    b = D["builds"][f"Staff_L{L}"]
    hit, _ = per_cast(b, bolt, L)
    burn_tick = max(e["burn_min_per_tick"], hit * e["burn_hit_pct"])
    vals[L] = (hit,
               burn_tick * e["burn_duration"],                      # 1-stack burn
               burn_tick * e["burn_duration"] * e["burn_max_stacks"],  # saturated
               hit * e["lightning_bonus_mult"],
               hit * e["lightning_chain_mult"] * e["lightning_chain_max_hops"])
lines.append("| FIRE | stacking burn (%.0f%%/hit/s, %ds, x%d stacks) | 1-stack: %.0f / %.0f / %.0f - saturated: %.0f / %.0f / %.0f |" % (
    e["burn_hit_pct"] * 100, e["burn_duration"], e["burn_max_stacks"],
    vals[1][1], vals[5][1], vals[10][1], vals[1][2], vals[5][2], vals[10][2]))
lines.append("| ICE | %d%% slow, %.1fs (no damage; feeds CHILL tag -> Thermal Shock) | 0 / 0 / 0 |" % (
    e["slow_pct"] * 100, e["slow_duration"]))
lines.append("| LIGHTNING | shock %.0f%% of hit + chain x%d hops at %.0f%% | %.0f / %.0f / %.0f |" % (
    e["lightning_bonus_mult"] * 100, e["lightning_chain_max_hops"], e["lightning_chain_mult"] * 100,
    vals[1][3] + vals[1][4], vals[5][3] + vals[5][4], vals[10][3] + vals[10][4]))
lines.append("")

# ── pair synergies ───────────────────────────────────────────────────────────
p, g = META["pair"], META["gauges"]
lines += ["## Weapon-pair synergy add-ons (on a representative avg hit)", "",
          "| Pair (active weapon) | Mechanic | L1 | L5 | L10 | Duo standing |",
          "|---|---|---|---|---|---|"]


def rep_hit(w, L):
    """Representative hit: the weapon's cheapest spammable damage ability."""
    best = None
    for ab in D["abilities"][w]:
        ls = ab["levels"][str(L)]
        if ls["damage_percent"] <= 0:
            continue
        if best is None or ls["cooldown"] < best[1]:
            h, _ = per_cast(D["builds"][f"{w}_L{L}"], ab, L)
            best = (h, ls["cooldown"], ab["name"])
    return best


rows = [
    ("Sword+Staff (sword)", "stance rider on sword abilities", lambda L: vals[L][1], "basic hits carry stance too"),
    ("Sword+Staff (staff)", "spell spends %d combo x %.2f" % (g["combo_cap"], p["staff_sword_combo_mult"]),
     lambda L: rep_hit("Staff", L)[0] * g["combo_cap"] * p["staff_sword_combo_mult"], "spend pays DOUBLE on swap-in"),
    ("Sword+Bow (bow)", "bow hits bank combo (stored value)",
     lambda L: rep_hit("Sword", L)[0] * g["combo_cap"] * p["sword_dagger_combo_mult"], "every 3rd hit banks extra"),
    ("Sword+Dagger (sword)", "poison imbue (saturated %d stacks x %ds)" % (p["poison_max_stacks"], p["poison_duration"]),
     lambda L: rep_hit("Sword", L)[0] * p["poison_per_tick_frac"] * p["poison_max_stacks"] * p["poison_duration"],
     "ambush spend %.2f -> %.2f" % (p["sword_dagger_combo_mult"], p["duo_sword_dagger_combo_mult"])),
    ("Sword+Dagger (dagger)", "ambush spends %d combo x %.2f" % (g["combo_cap"], p["sword_dagger_combo_mult"]),
     lambda L: rep_hit("Dagger", L)[0] * g["combo_cap"] * p["sword_dagger_combo_mult"], "x%.2f mult" % p["duo_sword_dagger_combo_mult"]),
    ("Bow+Staff (bow)", "stance rider on arrows", lambda L: vals[L][1], "—"),
    ("Bow+Staff (staff)", "spell rides %d momentum x %.3f" % (g["momentum_max_stacks"], g["momentum_damage_per_stack"]),
     lambda L: rep_hit("Staff", L)[0] * g["momentum_max_stacks"] * g["momentum_damage_per_stack"],
     "ride x%.1f" % p["duo_momentum_ride_mult"]),
    ("Bow+Dagger (bow)", "poison imbue per hit",
     lambda L: rep_hit("Bow", L)[0] * p["poison_per_tick_frac"] * p["poison_max_stacks"] * p["poison_duration"],
     "stacks %d -> %d" % (p["poison_max_stacks"], p["duo_poison_max_stacks"])),
    ("Bow+Dagger (dagger)", "ambush spends %d charge x %.2f" % (p["bd_charge_cap"], p["bow_dagger_charge_mult"]),
     lambda L: rep_hit("Dagger", L)[0] * p["bd_charge_cap"] * p["bow_dagger_charge_mult"],
     "cap %d -> %d" % (p["bd_charge_cap"], p["duo_bd_charge_cap"])),
    ("Staff+Dagger (staff)", "spell poison imbue (saturated)",
     lambda L: rep_hit("Staff", L)[0] * p["poison_per_tick_frac"] * p["poison_max_stacks"] * p["poison_duration"],
     "stacks %d -> %d" % (p["poison_max_stacks"], p["duo_poison_max_stacks"])),
    ("Staff+Dagger (dagger)", "ambush carries stance (fire shown)", lambda L: vals[L][1], "carries stance TWICE on swap-in"),
]
for name, mech, fn, duo in rows:
    lines.append("| %s | %s | %.0f | %.0f | %.0f | %s |" % (name, mech, fn(1), fn(5), fn(10), duo))
lines.append("")

# ── compensators: what the base model can't see, quantified ────────────────
SC = META["script_constants"]
CRIT_AVG_BASE = 1.35  # combat.gd: randf_range(1.2, 1.5) + CRITDAMAGE/100

lines += ["## Compensators — identity mechanics the base tables exclude, quantified (L10)", "",
          "| Discipline | Crit uplift | Identity mechanic | Quantified |",
          "|---|---|---|---|"]
crit_up = {}
for w in WEAPONS:
    b = D["builds"][f"{w}_L10"]
    p_crit = b["totals"].get("10", b["totals"].get(10, 0)) / 100.0
    cd_bon = b["totals"].get("11", b["totals"].get(11, 0)) / 100.0
    mult = CRIT_AVG_BASE + cd_bon
    crit_up[w] = 1 + p_crit * (mult - 1)
ident = {
    "Sword": ("combo finisher: x(1+%dx%.0f) = x%.0f on the spender; 3-build+1-spend cycle"
              % (SC["sword_combo"]["COMBO_CAP"], SC["sword_combo"]["COMBO_DAMAGE_PER_POINT"],
                 1 + SC["sword_combo"]["COMBO_CAP"] * SC["sword_combo"]["COMBO_DAMAGE_PER_POINT"]),
     "finisher slot ~x%.2f sustained ((3 basics + x4 spend)/4)" % ((3 + 4) / 4.0)),
    "Bow": ("Momentum ramp: +%.1f%%/stack, cap %d" % (
        SC["bow_momentum"]["DAMAGE_PER_STACK"] * 100, SC["bow_momentum"]["MAX_STACKS"]),
     "x%.2f on EVERY bow hit at full gauge (+ Snipe consume burst on top)" % (
        1 + SC["bow_momentum"]["MAX_STACKS"] * SC["bow_momentum"]["DAMAGE_PER_STACK"])),
    "Staff": ("element rider on every spell hit (fire shown)",
     "+%.0f%% of each hit as burn over %ds (saturated x%d), already tabled above" % (
        META["element"]["burn_hit_pct"] * 100 * META["element"]["burn_duration"],
        META["element"]["burn_duration"], META["element"]["burn_max_stacks"])),
    "Dagger": ("ambush opener: x%.1f AND guaranteed crit (shadowmeld)" % SC["shadowmeld"]["AMBUSH_DAMAGE_MULT"],
     "opener multiplier x%.2f vs an un-ambushed hit; plus Eviscerate execute (+%.0f%% max-range under 35%% HP)" % (
        SC["shadowmeld"]["AMBUSH_DAMAGE_MULT"] * (CRIT_AVG_BASE + D["builds"]["Dagger_L10"]["totals"].get("11", 0) / 100.0),
        SC["eviscerate"]["EXECUTE_BONUS_PCT"] * 100)),
}
for w in WEAPONS:
    lines.append("| %s | x%.3f (%.0f%% chance) | %s | %s |" % (
        w, crit_up[w], D["builds"][f"{w}_L10"]["totals"].get("10", 0), ident[w][0], ident[w][1]))
lines += ["",
          "Illustrative L10 medians with compensators folded in (median ability DPS x crit "
          "uplift x sustained identity factor; dagger identity factor uses one ambush opener "
          "per 4-hit rotation, sword the finisher-cycle factor, bow full-gauge Momentum, "
          "staff +fire rider on the median hit):", ""]
sustained = {"Sword": (3 + 4) / 4.0, "Bow": 1 + SC["bow_momentum"]["MAX_STACKS"] * SC["bow_momentum"]["DAMAGE_PER_STACK"],
             "Staff": 1 + META["element"]["burn_hit_pct"] * META["element"]["burn_duration"],
             "Dagger": (3 + SC["shadowmeld"]["AMBUSH_DAMAGE_MULT"] * (CRIT_AVG_BASE + D["builds"]["Dagger_L10"]["totals"].get("11", 0) / 100.0)) / 4.0}
lines += ["| Discipline | base median DPS | crit | identity | effective |", "|---|---|---|---|---|"]
eff = {}
for w in WEAPONS:
    dps = []
    for ab in D["abilities"][w]:
        ls = ab["levels"]["10"]
        if ls["damage_percent"] <= 0 or ls["cooldown"] <= 0:
            continue
        _, cast = per_cast(D["builds"][f"{w}_L10"], ab, 10)
        dps.append(cast / ls["cooldown"])
    base = statistics.median(dps)
    eff[w] = base * crit_up[w] * sustained[w]
    lines.append("| %s | %.1f | x%.3f | x%.2f | %.1f |" % (w, base, crit_up[w], sustained[w], eff[w]))
med_eff = statistics.median(eff.values())
for w, v in eff.items():
    if abs(v - med_eff) / med_eff > 0.30:
        issues.append("**effective divergence (L10, compensators folded):** %s %.1f vs median %.1f (%+.0f%%)."
                      % (w, v, med_eff, 100 * (v - med_eff) / med_eff))
lines.append("")

# ── inconsistency sweep ──────────────────────────────────────────────────────
# 1. damage_stat mismatches (staff damage abilities must scale MAGICATTACK and
#    vice versa - the wrong stat is 0 on that build = zero damage).
for w in WEAPONS:
    want = 13 if w == "Staff" else 12
    for ab in D["abilities"][w]:
        if all(ab["levels"][str(l)]["damage_percent"] == 0 for l in LEVELS):
            continue
        if ab["damage_stat"] != want:
            issues.append("**damage_stat mismatch:** %s ability `%s` has damage_stat=%d (%s) — "
                          "computes vs an attack stat that is ~0 on a %s build."
                          % (w, ab["name"], ab["damage_stat"],
                             "WEAPONATTACK" if ab["damage_stat"] == 12 else "MAGICATTACK", w))

# 2. damage that never grows while mana does
for w in WEAPONS:
    for ab in D["abilities"][w]:
        l1, l10 = ab["levels"]["1"], ab["levels"]["10"]
        if l1["damage_percent"] > 0 and l1["damage_percent"] == l10["damage_percent"] and ab["max_level"] >= 10:
            note = " (mana DOES grow %d->%d)" % (l1["mana"], l10["mana"]) if l10["mana"] > l1["mana"] else ""
            issues.append("**flat damage curve:** %s `%s` deals %d%% at every level%s." % (w, ab["name"], l1["damage_percent"], note))

# 3. zero-cost / zero-cooldown damage actives
for w in WEAPONS:
    for ab in D["abilities"][w]:
        l10 = ab["levels"]["10"]
        if l10["damage_percent"] > 0 and l10["cooldown"] <= 0:
            issues.append("**no cooldown:** %s `%s` deals damage with cooldown 0." % (w, ab["name"]))
        if l10["damage_percent"] > 0 and l10["mana"] <= 0:
            issues.append("**free cast:** %s `%s` deals damage with mana cost 0." % (w, ab["name"]))

# 4. discipline throughput divergence at L10
tot = {}
for w in WEAPONS:
    dps = []
    for ab in D["abilities"][w]:
        ls = ab["levels"]["10"]
        if ls["damage_percent"] <= 0 or ls["cooldown"] <= 0:
            continue
        _, cast = per_cast(D["builds"][f"{w}_L10"], ab, 10)
        dps.append(cast / ls["cooldown"])
    tot[w] = statistics.median(dps)
med = statistics.median(tot.values())
for w, v in tot.items():
    if abs(v - med) / med > 0.30:
        issues.append("**discipline divergence (L10):** %s median ability DPS %.1f vs cross-weapon median %.1f (%+.0f%%)."
                      % (w, v, med, 100 * (v - med) / med))

# 5. per-weapon DPS outliers at L10. Utility-identity abilities (mark
#    appliers, summons whose damage accrues over a duration, CC/buff zones)
#    are excluded from LOW flags - their value is the payoff, not the hit.
UTILITY_IDENTITY = {"Mark of the Hunt", "Death Mark", "Sentinel's Mark", "Mana Surge",
                    "Shadow Partner", "Arcane Familiar", "Smoke Bomb", "Banner of the Vanguard"}
rotation = {}
for w in WEAPONS:
    rows_d = []
    for ab in D["abilities"][w]:
        ls = ab["levels"]["10"]
        if ls["damage_percent"] <= 0 or ls["cooldown"] <= 0:
            continue
        _, cast = per_cast(D["builds"][f"{w}_L10"], ab, 10)
        rows_d.append((ab["name"], cast / ls["cooldown"]))
    m = statistics.median(v for _, v in rows_d)
    rotation[w] = statistics.mean(sorted((v for _, v in rows_d), reverse=True)[:3])
    for n, v in rows_d:
        if v > 2.5 * m:
            issues.append("**DPS outlier (high):** %s `%s` %.1f dps vs weapon median %.1f (x%.1f)." % (w, n, v, m, v / m))
        elif v < 0.3 * m and n not in UTILITY_IDENTITY:
            issues.append("**DPS outlier (low):** %s `%s` %.1f dps vs weapon median %.1f (x%.2f)." % (w, n, v, m, v / m))

# 5b. rotation-core comparison: mean of each weapon's top-3 ability DPS - a
#     fairer cross-discipline lens than the median (half of Dagger's kit is
#     utility by identity, which drags its median without weakening its
#     actual damage rotation).
med_rot = statistics.median(rotation.values())
for w, v in rotation.items():
    if abs(v - med_rot) / med_rot > 0.30:
        issues.append("**rotation-core divergence (L10, top-3 mean):** %s %.1f vs median %.1f (%+.0f%%)."
                      % (w, v, med_rot, 100 * (v - med_rot) / med_rot))
issues.append("**doc note:** sword finishers spend combo at +100%%/point (x4; Power Strike x7) per "
              "COMBO_DAMAGE_PER_POINT's deliberate tuning history - the sword_combo.gd header said "
              "+25%%/point and has been corrected. This finisher ceiling is the main driver of the "
              "sword-vs-dagger effective gap; rebalance is a design call.")

# 6. element rider imbalance (fire saturated vs lightning, same hit)
fire10, light10 = vals[10][2], vals[10][3] + vals[10][4]
if max(fire10, light10) > 2.0 * max(1e-9, min(fire10, light10)):
    issues.append("**element imbalance:** saturated FIRE burn %.0f vs LIGHTNING %.0f per hit at Staff L10 (x%.1f) — "
                  "plus ICE deals 0 (utility-only by design, but it competes with these for the same stance slot)."
                  % (fire10, light10, max(fire10, light10) / max(1e-9, min(fire10, light10))))

# 7. max_range sanity per build
for w in WEAPONS:
    for L in LEVELS:
        b = D["builds"][f"{w}_L{L}"]
        live = b["max_range_by_stat"][MAG_ATK if w == "Staff" else WPN_ATK]
        if live <= 0:
            issues.append("**dead build:** %s L%d max_range is %d." % (w, L, live))

lines += ["## Inconsistency sweep", ""]
lines += [("- " + i) for i in issues] if issues else ["- none found"]
lines.append("")
open(OUT, "w").write("\n".join(lines))
print(f"wrote {OUT} with {len(issues)} findings")
for i in issues:
    print(" *", i)
